<<<<<<< HEAD
# Generated by Django 3.2.9 on 2022-11-13 16:37
=======
# Generated by Django 4.0.8 on 2022-11-30 19:54
>>>>>>> 7a59026 (Final Sprint)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
<<<<<<< HEAD
                ('photo', models.ImageField(blank=True, upload_to='users/%d/%m/%Y/')),
=======
                ('location', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
>>>>>>> 7a59026 (Final Sprint)
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
