# Generated by Django 4.0.8 on 2022-12-03 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='articles',
            name='content',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='articles',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='articles',
            name='published_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='articles',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='url_to_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
