# Generated by Django 4.0.8 on 2022-12-03 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_articles_author_articles_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='content',
        ),
    ]
