# Generated by Django 4.0.8 on 2022-12-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_remove_articles_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='articles',
            name='url_to_image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
