# Generated by Django 4.0.8 on 2022-12-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(blank=True, default='Author', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
